---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(infer)
library(gridExtra)
remotes::install_gitlab("00000000014BADCE/chisquaredtest", auth_token = "glpat-s_hG6kgpx_CY7Pb4VbXm", host = "gitlab.lrz.de")
library(chisquaredtest)
```

# 1. Überblick

This package performs Chi-squared tests and visualizes the data. 

# 2. Installation

You can install the development version of chisquaredtest like so:

``` r
remotes::install_gitlab("00000000014BADCE/chisquaredtest", auth_token = "glpat-s_hG6kgpx_CY7Pb4VbXm", host = "gitlab.lrz.de")
```

# 3. Explorative Analyse

```{r}
sample_function()
```


```{r}
p1 <- var_bar_chart("Mathematics", "Biology")
p2 <-  var_bar_chart("Mathematics", "Shopping")
p3 <- var_bar_chart("Mathematics", "Pets")
combine_bar_charts(p1, p2, p3)
```
```{r}
p1 <- one_var_pie_chart("Art exhibitions")
p2 <- one_var_pie_chart("Chemistry")
p3 <- one_var_pie_chart("Dancing")
combine_pie_charts(p1, p2, p3)
```


# 4. Induktive Analyse

```{r}
visualize_chi_squared_test("Mathematics", "Biology")
```
```{r}
visualize_chi_squared_test("Pets", "Cars")
```
```{r}
visualize_chi_squared_test("Mathematics", "Physics")
```


